In [21]:
import torch

In [22]:
x = torch.arange(0, 4.0, 1.0)
x

tensor([0., 1., 2., 3.])

In [23]:
# Can also create x = torch.arange(4.0, requires_grad=True)
x.requires_grad_(True)
x.grad  # The gradient is None by default

In [24]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [25]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [26]:
x.grad == 4 * x

tensor([True, True, True, True])

In [27]:
x.grad.zero_()  # Reset the gradient
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [30]:
x.grad.zero_()
y = x * x
# below we add the partial derivatives
y.backward(gradient=torch.ones(len(y)))  # Faster: y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])