In [1]:
# from d2l import torch as d2l  # Use PyTorch as the backend
import torch

In [2]:
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [3]:
x.numel()

12

In [4]:
x.shape

torch.Size([12])

In [5]:
X = x.reshape(3, 4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [6]:
X = x.reshape(3, -1) # -1 means autoinfer
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [7]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [8]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [9]:
torch.randn(3, 4) # drawn from gaussian mu=0 sigma=1

tensor([[ 0.1670,  1.1167,  1.3507,  1.1351],
        [-2.7131,  1.2618, -1.5569,  0.1542],
        [-0.1276,  2.0857,  0.2085, -0.4436]])

In [10]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [11]:
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [12]:
X[1, 2] = 17
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5., 17.,  7.],
        [ 8.,  9., 10., 11.]])

In [13]:
X[:2, :] = 12
X


tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [14]:
torch.exp(x) # element-wise

tensor([162754.7969, 162754.7969, 162754.7969, 162754.7969, 162754.7969,
        162754.7969, 162754.7969, 162754.7969,   2980.9580,   8103.0840,
         22026.4648,  59874.1406])

In [15]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y # elementwise

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [16]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]]) # first element float -> tensor is float
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [17]:
X == Y ## elementwise

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [18]:
X.sum() # elementwise

tensor(66.)

In [19]:
X.sum().shape # scaler -> shape is empty array

torch.Size([])

In [20]:
torch.tensor([]).shape

torch.Size([0])

In [21]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [22]:
a + b # broadcasting, section 2.1.4 for reference

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [23]:
before = id(Y)
Y = Y + X
id(Y) == before

False

In [25]:
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y # elementwise, inplace assignment
print('id(Z):', id(Z))

id(Z): 140632058348944
id(Z): 140632058348944


In [26]:
before = id(X)
X += Y # also inplace
id(X) == before

True

In [27]:
A = X.numpy()
B = torch.from_numpy(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [29]:
A, B

(array([[ 2.,  3.,  8.,  9.],
        [ 9., 12., 15., 18.],
        [20., 21., 22., 23.]], dtype=float32),
 tensor([[ 2.,  3.,  8.,  9.],
         [ 9., 12., 15., 18.],
         [20., 21., 22., 23.]]))

In [30]:
A[1,2] = 0
A, B # memory is shared so be careful!

(array([[ 2.,  3.,  8.,  9.],
        [ 9., 12.,  0., 18.],
        [20., 21., 22., 23.]], dtype=float32),
 tensor([[ 2.,  3.,  8.,  9.],
         [ 9., 12.,  0., 18.],
         [20., 21., 22., 23.]]))

In [28]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a) # scaler unpacking

(tensor([3.5000]), 3.5, 3.5, 3)

In [34]:
sum = B.sum() # works for tensor scaler outputs too
sum, sum.item(), float(sum), int(sum) # scaler unpacking

(tensor(147.), 147.0, 147.0, 147)