In [2]:
import torch

In [3]:
A = torch.arange(6, dtype=torch.float32).reshape(2, 3)
B = A.clone()  # Assign a copy of A to B by allocating new memory
A, A + B


(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[ 0.,  2.,  4.],
         [ 6.,  8., 10.]]))

In [11]:
A.shape, A.sum(dim=0).shape, A.sum(dim=0), A.sum(dim=1)

(torch.Size([2, 3]), torch.Size([3]), tensor([3., 5., 7.]), tensor([ 3., 12.]))

In [15]:
sum_A = A.sum(dim=1, keepdim=True)
sum_A, sum_A.shape

(tensor([[ 3.],
         [12.]]),
 torch.Size([2, 1]))

In [16]:
A / sum_A

tensor([[0.0000, 0.3333, 0.6667],
        [0.2500, 0.3333, 0.4167]])

In [19]:
A, A.cumsum(dim=0), A.cumsum(dim=1)

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[0., 1., 2.],
         [3., 5., 7.]]),
 tensor([[ 0.,  1.,  3.],
         [ 3.,  7., 12.]]))

In [21]:
x = torch.arange(3, dtype=torch.float32)
y = torch.ones(3, dtype = torch.float32)
x, y, torch.dot(x, y), torch.outer(x, y)

(tensor([0., 1., 2.]),
 tensor([1., 1., 1.]),
 tensor(3.),
 tensor([[0., 0., 0.],
         [1., 1., 1.],
         [2., 2., 2.]]))

In [22]:
A.shape, x.shape, torch.mv(A, x), A@x

(torch.Size([2, 3]), torch.Size([3]), tensor([ 5., 14.]), tensor([ 5., 14.]))

In [26]:
B = torch.ones(3, 4)
A.shape, B.shape, torch.mm(A, B), A@B

(torch.Size([2, 3]),
 torch.Size([3, 4]),
 tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]),
 tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]))

In [31]:
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

In [33]:
torch.abs(u).sum() # l1 norm

tensor(7.)

In [34]:
torch.norm(torch.ones((4, 9)))

tensor(6.)